services:
  mysql:
    image: mysql:8.0
    container_name: zaposljavanje-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zaposljavanje_db
      MYSQL_USER: zaposljavanje_user
      MYSQL_PASSWORD: zaposljavanje1234
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
